before_script:
  - psql -c 'create database jollygoodcode_test;' -U postgres
language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.1
  - 2.3.0
  - 2.2.5
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
