# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ffc5f415b96455f2e1476c0b419c23f69bf4c3e57ee23eb6b61f47b9f1c5ac67ef9c100b624b02fc2087018d1b49cb80983994d6fa4f6786144c2710f5effbd

test:
  secret_key_base: 26307f30ccc5b30259ea771e98e96f57e1cf5af695d5c8e13b10b850d8b78d3c1099bdfb41244b9289b2869f72680e62da716a2cc44889d29b28ebf6c9f734d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
